[package]
name = "compository"
version = "0.1.0"
authors = ["Rasmus Eneman <rasmus@eneman.eu>"]
edition = "2018"

[lib]
# crate-type = ["staticlib", "cdylib"]
crate-type = ["dylib"]

[dependencies]
xkb = "0.2.0"
xkbcommon-sys = "0.7.4"

[build-dependencies]
cbindgen = "0.9.0"
