[package]
name = "rust_wm"
version = "0.1.0"
authors = ["Rasmus Eneman <rasmus@eneman.eu>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
wlroots_rs = { path = "../wlroots_rs"}
xkbcommon = "0.4.0"
wayland-server = "0.23.5"

[build-dependencies]
cbindgen = "0.9.1"
